### ISSUE TITLE
Not working on GNOME 3.38 - Fedora 33

### ISSUE THREAD

**Issue by tosziro** [hardpixel/unite-shell#199]
Unite is not working on current GNOME 3.38 

Shows error: _controls.unparent is not a function_

**Comment by jonian** [comment]
Hi @tosziro, thanks for the report. I will add GNOME 3.38 support when Arch Linux receives the update. If you can make a PR that fixes the issues, I will happily merge it.
